update

diff --git a/services/php/Dockerfile b/services/php/Dockerfile
--- a/services/php/Dockerfile
+++ b/services/php/Dockerfile
@@ -1,41 +1,89 @@
-ARG PHP_VERSION
-FROM ${PHP_VERSION}
+ARG LARADOCK_PHP_VERSION
+FROM laradock/php-fpm:latest-${LARADOCK_PHP_VERSION}
 
-ARG TZ
-ARG CONTAINER_PACKAGE_URL
+ARG LARADOCK_PHP_VERSION
 
+# Set Environment Variables
+ENV DEBIAN_FRONTEND noninteractive
 
-RUN if [ $CONTAINER_PACKAGE_URL ] ; then sed -i "s/dl-cdn.alpinelinux.org/${CONTAINER_PACKAGE_URL}/g" /etc/apk/repositories ; fi
+RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list && \
+    sed -i 's/security.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list && \
+    sed -i 's/security-cdn.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list \
 
+# always run apt update when start and after add new source list, then clean up at end.
+RUN set -xe; \
+    apt-get update -yqq && \
+    pecl channel-update pecl.php.net && \
+    apt-get install -yqq \
+      apt-utils \
+      gnupg2 \
+      git \
+      #
+      #--------------------------------------------------------------------------
+      # Mandatory Software's Installation
+      #--------------------------------------------------------------------------
+      #
+      # Mandatory Software's such as ("mcrypt", "pdo_mysql", "libssl-dev", ....)
+      # are installed on the base image 'laradock/php-fpm' image. If you want
+      # to add more Software's or remove existing one, you need to edit the
+      # base image (https://github.com/Laradock/php-fpm).
+      #
+      # next lines are here becase there is no auto build on dockerhub see https://github.com/laradock/laradock/pull/1903#issuecomment-463142846
+      libzip-dev zip unzip && \
+      if [ ${LARADOCK_PHP_VERSION} = "7.3" ] || [ ${LARADOCK_PHP_VERSION} = "7.4" ] || [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then \
+        docker-php-ext-configure zip; \
+      else \
+        docker-php-ext-configure zip --with-libzip; \
+      fi && \
+      # Install the zip extension
+      docker-php-ext-install zip && \
+      php -m | grep -q 'zip'
 
-COPY ./extensions /tmp/extensions
-WORKDIR /tmp/extensions
-RUN chmod +x install.sh \
-    && sh install.sh
+#
+#--------------------------------------------------------------------------
+# Optional Software's Installation
+#--------------------------------------------------------------------------
+#
+RUN apt-get -yqq install libbz2-dev \
+    && docker-php-ext-install bz2 \
+    && docker-php-ext-install mysqli
 
+###########################################################################
+# Check PHP version:
+###########################################################################
 
-ADD https://ghproxy.com/https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
+RUN set -xe; php -v | head -n 1 | grep -q "PHP ${LARADOCK_PHP_VERSION}."
 
-RUN chmod uga+x /usr/local/bin/install-php-extensions
+#
+#--------------------------------------------------------------------------
+# Final Touch
+#--------------------------------------------------------------------------
+#
 
-RUN apk --no-cache add tzdata \
-    && cp "/usr/share/zoneinfo/$TZ" /etc/localtime \
-    && echo "$TZ" > /etc/timezone
+COPY ./laravel.ini /usr/local/etc/php/conf.d
+COPY ./xlaravel.pool.conf /usr/local/etc/php-fpm.d/
 
+USER root
 
-# Fix: https://github.com/docker-library/php/issues/1121
-RUN apk add --no-cache --repository http://${CONTAINER_PACKAGE_URL}/alpine/v3.13/community/ gnu-libiconv=1.15-r3
-ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
+# Clean up
+RUN apt-get clean && \
+    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
+    rm /var/log/lastlog /var/log/faillog
 
+# Configure non-root user.
+ARG PUID=
+ENV PUID ${PUID}
+ARG PGID=1000
+ENV PGID ${PGID}
 
-# Install composer and change it's cache home
-RUN chmod +x install-composer.sh \
-    && sh install-composer.sh \
-    && rm -rf /tmp/extensions
-ENV COMPOSER_HOME=/tmp/composer
+RUN groupmod -o -g 1000 www-data && \
+    usermod -o -u 1000 -g www-data www-data
 
-# php image's www-data user uid & gid are 82, change them to 1000 (primary user)
-RUN apk --no-cache add shadow && usermod -u 1000 www-data && groupmod -g 1000 www-data
+# Configure locale.
+ENV LC_ALL POSIX
 
+WORKDIR /var/www
 
-WORKDIR /www
+CMD ["php-fpm"]
+
+EXPOSE 9000
